name: Check, test, and publish to crates.io every tag (i.e. new version)

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@cargo-minimal-versions
      - name: Check
        run: cargo check --release --verbose
      - name: Run tests
        run: cargo test --release --verbose
      - name: Run tests with direct minimal versions
        run: cargo minimal-versions --direct test --verbose --release
      - run: cargo publish --token ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
